Initial import of ORD changes to ModelInterface code only.  This does not include any of the encancments source code at this point which is still being referenced from an external .jar.
TODO: there was compile error which needs to be addressed properly:
/ModelInterface/ModelGUI2/QueryResultsPanel.java:266: error: cannot find symbol				ModelInterfaceUtil.getUnit(qg, (String) jTable.getValueAt(0, jTable.getColumnCount() - 1)), path, //@1				                  ^  symbol:   method getUnit(QueryGenerator,String)  location: class ModelInterfaceUtil